// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permisos.proto

package com.permisosservicegrpc.grpc;

public interface PermisoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PermisoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string cedula_medico = 1;</code>
   */
  java.lang.String getCedulaMedico();
  /**
   * <code>optional string cedula_medico = 1;</code>
   */
  com.google.protobuf.ByteString
      getCedulaMedicoBytes();

  /**
   * <code>optional string id_paciente = 2;</code>
   */
  java.lang.String getIdPaciente();
  /**
   * <code>optional string id_paciente = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdPacienteBytes();

  /**
   * <code>optional string nombre_archivo = 3;</code>
   */
  java.lang.String getNombreArchivo();
  /**
   * <code>optional string nombre_archivo = 3;</code>
   */
  com.google.protobuf.ByteString
      getNombreArchivoBytes();
}
