// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permisos.proto

package com.permisosservicegrpc.grpc;

/**
 * Protobuf type {@code PermisoRequest}
 */
public  final class PermisoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PermisoRequest)
    PermisoRequestOrBuilder {
  // Use PermisoRequest.newBuilder() to construct.
  private PermisoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PermisoRequest() {
    cedulaMedico_ = "";
    idPaciente_ = "";
    nombreArchivo_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PermisoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cedulaMedico_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            idPaciente_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nombreArchivo_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.permisosservicegrpc.grpc.Permisos.internal_static_PermisoRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.permisosservicegrpc.grpc.Permisos.internal_static_PermisoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.permisosservicegrpc.grpc.PermisoRequest.class, com.permisosservicegrpc.grpc.PermisoRequest.Builder.class);
  }

  public static final int CEDULA_MEDICO_FIELD_NUMBER = 1;
  private volatile java.lang.Object cedulaMedico_;
  /**
   * <code>optional string cedula_medico = 1;</code>
   */
  public java.lang.String getCedulaMedico() {
    java.lang.Object ref = cedulaMedico_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cedulaMedico_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cedula_medico = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCedulaMedicoBytes() {
    java.lang.Object ref = cedulaMedico_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cedulaMedico_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_PACIENTE_FIELD_NUMBER = 2;
  private volatile java.lang.Object idPaciente_;
  /**
   * <code>optional string id_paciente = 2;</code>
   */
  public java.lang.String getIdPaciente() {
    java.lang.Object ref = idPaciente_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idPaciente_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id_paciente = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdPacienteBytes() {
    java.lang.Object ref = idPaciente_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idPaciente_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOMBRE_ARCHIVO_FIELD_NUMBER = 3;
  private volatile java.lang.Object nombreArchivo_;
  /**
   * <code>optional string nombre_archivo = 3;</code>
   */
  public java.lang.String getNombreArchivo() {
    java.lang.Object ref = nombreArchivo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nombreArchivo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nombre_archivo = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNombreArchivoBytes() {
    java.lang.Object ref = nombreArchivo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nombreArchivo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCedulaMedicoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cedulaMedico_);
    }
    if (!getIdPacienteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idPaciente_);
    }
    if (!getNombreArchivoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nombreArchivo_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCedulaMedicoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cedulaMedico_);
    }
    if (!getIdPacienteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idPaciente_);
    }
    if (!getNombreArchivoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nombreArchivo_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.permisosservicegrpc.grpc.PermisoRequest)) {
      return super.equals(obj);
    }
    com.permisosservicegrpc.grpc.PermisoRequest other = (com.permisosservicegrpc.grpc.PermisoRequest) obj;

    boolean result = true;
    result = result && getCedulaMedico()
        .equals(other.getCedulaMedico());
    result = result && getIdPaciente()
        .equals(other.getIdPaciente());
    result = result && getNombreArchivo()
        .equals(other.getNombreArchivo());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CEDULA_MEDICO_FIELD_NUMBER;
    hash = (53 * hash) + getCedulaMedico().hashCode();
    hash = (37 * hash) + ID_PACIENTE_FIELD_NUMBER;
    hash = (53 * hash) + getIdPaciente().hashCode();
    hash = (37 * hash) + NOMBRE_ARCHIVO_FIELD_NUMBER;
    hash = (53 * hash) + getNombreArchivo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.permisosservicegrpc.grpc.PermisoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.permisosservicegrpc.grpc.PermisoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PermisoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PermisoRequest)
      com.permisosservicegrpc.grpc.PermisoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.permisosservicegrpc.grpc.Permisos.internal_static_PermisoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.permisosservicegrpc.grpc.Permisos.internal_static_PermisoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.permisosservicegrpc.grpc.PermisoRequest.class, com.permisosservicegrpc.grpc.PermisoRequest.Builder.class);
    }

    // Construct using com.permisosservicegrpc.grpc.PermisoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cedulaMedico_ = "";

      idPaciente_ = "";

      nombreArchivo_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.permisosservicegrpc.grpc.Permisos.internal_static_PermisoRequest_descriptor;
    }

    public com.permisosservicegrpc.grpc.PermisoRequest getDefaultInstanceForType() {
      return com.permisosservicegrpc.grpc.PermisoRequest.getDefaultInstance();
    }

    public com.permisosservicegrpc.grpc.PermisoRequest build() {
      com.permisosservicegrpc.grpc.PermisoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.permisosservicegrpc.grpc.PermisoRequest buildPartial() {
      com.permisosservicegrpc.grpc.PermisoRequest result = new com.permisosservicegrpc.grpc.PermisoRequest(this);
      result.cedulaMedico_ = cedulaMedico_;
      result.idPaciente_ = idPaciente_;
      result.nombreArchivo_ = nombreArchivo_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.permisosservicegrpc.grpc.PermisoRequest) {
        return mergeFrom((com.permisosservicegrpc.grpc.PermisoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.permisosservicegrpc.grpc.PermisoRequest other) {
      if (other == com.permisosservicegrpc.grpc.PermisoRequest.getDefaultInstance()) return this;
      if (!other.getCedulaMedico().isEmpty()) {
        cedulaMedico_ = other.cedulaMedico_;
        onChanged();
      }
      if (!other.getIdPaciente().isEmpty()) {
        idPaciente_ = other.idPaciente_;
        onChanged();
      }
      if (!other.getNombreArchivo().isEmpty()) {
        nombreArchivo_ = other.nombreArchivo_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.permisosservicegrpc.grpc.PermisoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.permisosservicegrpc.grpc.PermisoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cedulaMedico_ = "";
    /**
     * <code>optional string cedula_medico = 1;</code>
     */
    public java.lang.String getCedulaMedico() {
      java.lang.Object ref = cedulaMedico_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cedulaMedico_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cedula_medico = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCedulaMedicoBytes() {
      java.lang.Object ref = cedulaMedico_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cedulaMedico_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cedula_medico = 1;</code>
     */
    public Builder setCedulaMedico(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cedulaMedico_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cedula_medico = 1;</code>
     */
    public Builder clearCedulaMedico() {
      
      cedulaMedico_ = getDefaultInstance().getCedulaMedico();
      onChanged();
      return this;
    }
    /**
     * <code>optional string cedula_medico = 1;</code>
     */
    public Builder setCedulaMedicoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cedulaMedico_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object idPaciente_ = "";
    /**
     * <code>optional string id_paciente = 2;</code>
     */
    public java.lang.String getIdPaciente() {
      java.lang.Object ref = idPaciente_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idPaciente_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string id_paciente = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdPacienteBytes() {
      java.lang.Object ref = idPaciente_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idPaciente_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id_paciente = 2;</code>
     */
    public Builder setIdPaciente(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idPaciente_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id_paciente = 2;</code>
     */
    public Builder clearIdPaciente() {
      
      idPaciente_ = getDefaultInstance().getIdPaciente();
      onChanged();
      return this;
    }
    /**
     * <code>optional string id_paciente = 2;</code>
     */
    public Builder setIdPacienteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idPaciente_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nombreArchivo_ = "";
    /**
     * <code>optional string nombre_archivo = 3;</code>
     */
    public java.lang.String getNombreArchivo() {
      java.lang.Object ref = nombreArchivo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombreArchivo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nombre_archivo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNombreArchivoBytes() {
      java.lang.Object ref = nombreArchivo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombreArchivo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nombre_archivo = 3;</code>
     */
    public Builder setNombreArchivo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nombreArchivo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nombre_archivo = 3;</code>
     */
    public Builder clearNombreArchivo() {
      
      nombreArchivo_ = getDefaultInstance().getNombreArchivo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string nombre_archivo = 3;</code>
     */
    public Builder setNombreArchivoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nombreArchivo_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PermisoRequest)
  }

  // @@protoc_insertion_point(class_scope:PermisoRequest)
  private static final com.permisosservicegrpc.grpc.PermisoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.permisosservicegrpc.grpc.PermisoRequest();
  }

  public static com.permisosservicegrpc.grpc.PermisoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PermisoRequest>
      PARSER = new com.google.protobuf.AbstractParser<PermisoRequest>() {
    public PermisoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PermisoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PermisoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PermisoRequest> getParserForType() {
    return PARSER;
  }

  public com.permisosservicegrpc.grpc.PermisoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

