// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permisos.proto

package com.permisosservicegrpc.grpc;

public interface PermisoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PermisoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool permiso = 1;</code>
   */
  boolean getPermiso();
}
