// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: permisos.proto

package com.permisosservicegrpc.grpc;

public final class Permisos {
  private Permisos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PermisoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PermisoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PermisoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PermisoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016permisos.proto\"<\n\016PermisoRequest\022\025\n\rce" +
      "dula_medico\030\001 \001(\t\022\023\n\013id_paciente\030\002 \001(\t\"\"" +
      "\n\017PermisoResponse\022\017\n\007permiso\030\001 \001(\0102D\n\017pe" +
      "rmisosService\0221\n\ngetPermiso\022\017.PermisoReq" +
      "uest\032\020.PermisoResponse\"\000B \n\034com.permisos" +
      "servicegrpc.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PermisoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PermisoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PermisoRequest_descriptor,
        new java.lang.String[] { "CedulaMedico", "IdPaciente", });
    internal_static_PermisoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PermisoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PermisoResponse_descriptor,
        new java.lang.String[] { "Permiso", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
